import { Service } from "@/services";

export const chainTypes: Record<string, { value: string; name: string; color: string; bg: string; }> = {
  near: {
    value: "near",
    name: "Near",
    color: "#56DEAD",
    bg: "linear-gradient(90deg, rgba(1, 237, 151, 0.20) 0%, rgba(1, 237, 151, 0.00) 50%)",
  },
  sol: {
    value: "sol",
    name: "Solana",
    color: "#987FF3",
    bg: "linear-gradient(90deg, rgba(248, 108, 255, 0.20) 0%, rgba(248, 108, 255, 0.00) 50%)",
  },
  evm: {
    value: "evm",
    name: "EVM",
    color: "#C4CAE1",
    bg: "linear-gradient(90deg, rgba(185, 215, 255, 0.20) 0%, rgba(185, 215, 255, 0.00) 50%)",
  },
  tron: {
    value: "tron",
    name: "Tron",
    color: "#F66273",
    bg: "linear-gradient(90deg, rgba(210, 31, 16, 0.20) 0%, rgba(210, 31, 16, 0.00) 50%)",
  },
  aptos: {
    value: "aptos",
    name: "Aptos",
    color: "#000000",
    bg: "linear-gradient(90deg, rgba(0, 0, 0, 0.20) 0%, rgba(0, 0, 0, 0.00) 50%)",
  },
};

const chains = {
  near: {
    chainName: "Near",
    chainIcon: "/chains/near.png",
    chainIconGray: "/chains/near-gray.png",
    chainType: chainTypes.near.value,
    blockExplorerUrl: "https://nearblocks.io/txns",
    primaryColor: "#76EA9E",
    services: [Service.OneClick],
  },
  sol: {
    chainName: "Solana",
    chainIcon: "/chains/solana.png",
    chainIconGray: "/chains/solana-gray.png",
    chainType: chainTypes.sol.value,
    blockExplorerUrl: "https://solscan.io/tx",
    primaryColor: "#B93EF0",
    services: [Service.OneClick, Service.Usdt0],
  },
  eth: {
    chainName: "Ethereum",
    chainIcon: "/chains/ethereum.png",
    chainIconGray: "/chains/ethereum-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 1,
    blockExplorerUrl: "https://etherscan.io/tx",
    primaryColor: "#7083ee",
    services: [Service.OneClick, Service.Usdt0],
  },
  arb: {
    chainName: "Arbitrum",
    chainIcon: "/chains/arbitrum.png",
    chainIconGray: "/chains/arbitrum-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 42161,
    blockExplorerUrl: "https://arbiscan.io/tx",
    primaryColor: "#4763A7",
    services: [Service.OneClick, Service.Usdt0],
  },
  bsc: {
    chainName: "BNB Chain",
    chainIcon: "/chains/bsc.png",
    chainIconGray: "/chains/bsc-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 56,
    blockExplorerUrl: "https://bscscan.com/tx",
    primaryColor: "#F1C144",
    services: [Service.OneClick],
  },
  avax: {
    chainName: "Avalanche",
    chainIcon: "/chains/avalanche.png",
    chainIconGray: "/chains/avalanche-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 43114,
    blockExplorerUrl: "https://snowtrace.io/tx",
    primaryColor: "#9D2620",
    services: [Service.OneClick],
  },
  base: {
    chainName: "Base",
    chainIcon: "/chains/base.png",
    chainIconGray: "/chains/base-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 8453,
    blockExplorerUrl: "https://basescan.org/tx",
    primaryColor: "#3137F6",
    services: [Service.OneClick],
  },
  pol: {
    chainName: "Polygon",
    chainIcon: "/chains/polygon.png",
    chainIconGray: "/chains/polygon-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 137,
    blockExplorerUrl: "https://polygonscan.com/tx",
    primaryColor: "#5A2AD1",
    services: [Service.OneClick, Service.Usdt0],
  },
  gnosis: {
    chainName: "Gnosis",
    chainIcon: "/chains/gnosis.png",
    chainIconGray: "/chains/gnosis-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 100,
    blockExplorerUrl: "https://gnosisscan.io/tx",
    primaryColor: "#285230",
    services: [Service.OneClick],
  },
  op: {
    chainName: "Optimism",
    chainIcon: "/chains/optimism.png",
    chainIconGray: "/chains/optimism-gray.png",
    chainType: chainTypes.evm.value,
    chainId: 10,
    blockExplorerUrl: "https://optimistic.etherscan.io/tx",
    primaryColor: "#B5271D",
    services: [Service.OneClick, Service.Usdt0],
  },
  tron: {
    chainName: "Tron",
    chainIcon: "/chains/tron.png",
    chainIconGray: "/chains/tron-gray.png",
    chainType: chainTypes.tron.value,
    blockExplorerUrl: "https://tronscan.org/tx",
    primaryColor: "#BC3221",
    services: [Service.OneClick, Service.Usdt0],
  },
  aptos: {
    chainName: "Aptos",
    chainIcon: "/chains/aptos.png",
    chainIconGray: "/chains/aptos-gray.png",
    chainType: chainTypes.aptos.value,
    blockExplorerUrl: "https://aptoscan.com/transaction",
    primaryColor: "#000000",
    services: [Service.OneClick],
  },
};

export default chains;
